compile_design /home/qlblue/anthony/raptor_regression/tests/design7/AL4S3B_FPGA_IP.v /home/qlblue/anthony/raptor_regression/tests/design7/AL4S3B_FPGA_QL_Reserved.v /home/qlblue/anthony/raptor_regression/tests/design7/AL4S3B_FPGA_Registers.v /home/qlblue/anthony/raptor_regression/tests/design7/AL4S3B_FPGA_Top.v /home/qlblue/anthony/raptor_regression/tests/design7/f512x8_512x8.v /home/qlblue/anthony/raptor_regression/tests/design7/f512x16_512x16.v /home/qlblue/anthony/raptor_regression/tests/design7/f512x32_512x32.v /home/qlblue/anthony/raptor_regression/tests/design7/i2c_master_bit_ctrl.v /home/qlblue/anthony/raptor_regression/tests/design7/i2c_master_byte_ctrl.v /home/qlblue/anthony/raptor_regression/tests/design7/i2c_master_defines.v /home/qlblue/anthony/raptor_regression/tests/design7/i2c_master_top.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_CmdQueue_Registers_dma.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_CmdQueue_StateMachine.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_CmdQueue_Top.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_CmdQueue_Tx_FIFO.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_CmdQueue.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_DMA_Registers.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_DMA_StateMachine.v /home/qlblue/anthony/raptor_regression/tests/design7/I2C_Master_w_DMA.v /home/qlblue/anthony/raptor_regression/tests/design7/LCD_controller_registers.v /home/qlblue/anthony/raptor_regression/tests/design7/LCD_Controller_StateMachine.v /home/qlblue/anthony/raptor_regression/tests/design7/r2048x8_2048x8.v /home/qlblue/anthony/raptor_regression/tests/design7/UART_16550_Interrupt_Control.v /home/qlblue/anthony/raptor_regression/tests/design7/UART_16550_Registers.v /home/qlblue/anthony/raptor_regression/tests/design7/UART_16550_Rx_FIFO.v /home/qlblue/anthony/raptor_regression/tests/design7/UART_16550_Rx_Logic.v /home/qlblue/anthony/raptor_regression/tests/design7/UART_16550_Tx_FIFO.v /home/qlblue/anthony/raptor_regression/tests/design7/UART_16550_Tx_Logic.v /home/qlblue/anthony/raptor_regression/tests/design7/UART_16550.v --part RAPIDMATRIX --pkg PU64 --top top --working_dir /home/qlblue/anthony/raptor_regression/result/design7 --load_qdc /home/qlblue/anthony/raptor_regression/tests/s3b_edif/design7.qdc
#load_design {/home/qlblue/anthony/raptor_regression/tests/s3b_edif/design7.edf} --load_qdc {/home/qlblue/anthony/raptor_regression/tests/s3b_edif/design7.qdc} --working_dir {/home/qlblue/anthony/raptor_regression/result/design7} --part RAPIDMATRIX --pkg PU64 --foundry GF --node 40
save_project  
run_till router 
run_sta  
run_pe  
save_project  
exit

